visual_feature_extractor_node:
  ros__parameters:
    use_compressed: false
    image_crop_x_min: 40
    image_crop_x_max: 600
    image_crop_y_min: 150
    image_crop_y_max: 300

neocortex_node:
  ros__parameters:
    # TemporalMemory parameters
    tm_column_dimensions: 2048
    tm_cells_per_column: 32
    tm_activation_threshold: 4
    tm_initial_permanence: 0.55
    tm_connected_permanence: 0.5
    tm_min_threshold: 1
    tm_max_new_synapse_count: 20
    tm_permanence_increment: 0.01
    tm_permanence_decrement: 0.01
    tm_predicted_segment_decrement: 0.0005
    tm_max_segments_per_cell: 100
    tm_max_synapses_per_segment: 100
    tm_seed: 42

spatial_view_cells_node:
  ros__parameters:
    theta_alpha: 390
    theta_rho: 3
    score_interval: 380
    exclude_recent_intervals: 100

pose_cells_node:
  ros__parameters:
    pc_dim_xy: 18
    pc_dim_th: 36
    pc_w_e_dim: 7
    pc_w_i_dim: 5
    pc_w_e_var: 1
    pc_w_i_var: 2
    pc_global_inhib: 0.00002
    vt_active_decay: 2.0
    pc_vt_inject_energy: 0.08
    pc_cell_x_size: 1.0
    exp_delta_pc_threshold: 2.0
    pc_vt_restore: 0.1
    # draw
    enable: true

experience_map_node:
  ros__parameters:
    exp_correction: 0.5
    exp_loops: 50
    exp_initial_em_deg: 194.0
    # draw
    enable: true

